name: chronos_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pydantic=2
  - pyarrow
  - ruff
  - httpx
  - pytest
  - tqdm
  - numba
  - ta-lib

  - pip
  - pip:
      - --index-url https://pypi.tuna.tsinghua.edu.cn/simple
      - akshare
      - streamlit